apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    app.kubernetes.io/component: redis
    app.kubernetes.io/name: jumpserver-redis-ha
    app.kubernetes.io/part-of: jumpserver
  name: jumpserver-redis-ha-announce-0
spec:
  ports:
  - name: server
    port: 6379
    protocol: TCP
    targetPort: redis
  - name: sentinel
    port: 26379
    protocol: TCP
    targetPort: sentinel
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: jumpserver-redis-ha
    statefulset.kubernetes.io/pod-name: jumpserver-redis-ha-server-0
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    app.kubernetes.io/component: redis
    app.kubernetes.io/name: jumpserver-redis-ha
    app.kubernetes.io/part-of: jumpserver
  name: jumpserver-redis-ha-announce-1
spec:
  ports:
  - name: server
    port: 6379
    protocol: TCP
    targetPort: redis
  - name: sentinel
    port: 26379
    protocol: TCP
    targetPort: sentinel
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: jumpserver-redis-ha
    statefulset.kubernetes.io/pod-name: jumpserver-redis-ha-server-1
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    app.kubernetes.io/component: redis
    app.kubernetes.io/name: jumpserver-redis-ha
    app.kubernetes.io/part-of: jumpserver
  name: jumpserver-redis-ha-announce-2
spec:
  ports:
  - name: server
    port: 6379
    protocol: TCP
    targetPort: redis
  - name: sentinel
    port: 26379
    protocol: TCP
    targetPort: sentinel
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: jumpserver-redis-ha
    statefulset.kubernetes.io/pod-name: jumpserver-redis-ha-server-2
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  annotations: null
  labels:
    app.kubernetes.io/component: redis
    app.kubernetes.io/name: jumpserver-redis-ha
    app.kubernetes.io/part-of: jumpserver
  name: jumpserver-redis-ha
spec:
  clusterIP: None
  ports:
  - name: server
    port: 6379
    protocol: TCP
    targetPort: redis
  - name: sentinel
    port: 26379
    protocol: TCP
    targetPort: sentinel
  selector:
    app.kubernetes.io/name: jumpserver-redis-ha
  type: ClusterIP