apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

commonLabels:
  jumpserver: guacamole

images:
- name: jumpserver:1.0
  newName: wojiushixiaobai/jms_guacamole
  newTag: 1.6.0

replicas:
- name: guacamole
  count: 3
