apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

commonLabels:
  jumpserver: guacamole

images:
- name: jumpserver:1.0
  newName: harbor.xylink.com/xylink/jms_guacamole
  newTag: 1.5.6

replicas:
- name: guacamole
  count: 1
