apiVersion: apps/v1
kind: Deployment
metadata:
  name: jumpserver
  labels:
    app: jumpserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jumpserver
  template:
    metadata:
      labels:
        app: jumpserver
    spec:
      containers:
      - name: jumpserver
        image: jumpserver:1.0
        # command: ["/bin/sh","-c","sleep 50000"]
        env:
          - name: SECRET_KEY
            value: "B3f2w8P2PfxIAS7s4URrD9YmSbtqX4vXdPUL217kL9XPUOWrdd"
          - name: BOOTSTRAP_TOKEN
            value: "7Q11Vz6R2J6BLAd9"
          - name: DB_HOST
            value: "bbbbbbbbb"
          - name: DB_PORT
            value: "3306"
          - name: DB_USER
            value: "jumpserver"
          - name: DB_PASSWORD
            value: "nnnnnnn"
          - name: DB_NAME
            value: "jumpserver"
          - name: REDIS_HOST
            value: redis
          - name: REDIS_PORT
            value: "6379"
          - name: REDIS_PASSWORD
            value: "8URXPL2x3HZMi7xoGTdk3Upj"
        ports:
        - containerPort: 8080
          name: app
          protocol: TCP
        - containerPort: 8070
          name: ws
          protocol: TCP
