apiVersion: apps/v1
kind: Deployment
metadata:
  name: jumpserver
  labels:
    app: jumpserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jumpserver
  template:
    metadata:
      labels:
        app: jumpserver
    spec:
      containers:
      - name: jumpserver
        image: jumpserver:1.0
        env:
          - name: SECRET_KEY
            value: B3f2w8P2PfxIAS7s4URrD9YmSbtqX4vXdPUL217kL9XPUOWrdd
          - name: BOOTSTRAP_TOKEN
            value: 7Q11Vz6R2J6BLAd9
          - name: DB_HOST
            value: rm-2zekkzz8l65nc7eq8.mysql.rds.aliyuncs.com
          - name: DB_PORT
            value: 3306
          - name: DB_USER
            value: jumpserver
          - name: DB_PASSWORD
            value: Wq7u0Bn8EABh3J91G
          - name: DB_NAME
            value: jumpserver
          - name: REDIS_HOST
            value: jumpserver-redis-ha
          - name: REDIS_PORT
            value: 26379
          - name: REDIS_PASSWORD
            value: 
        ports:
        - containerPort: 8080
          name: app
          protocol: tcp
        - containerPort: 8070
          name: app
          protocol: tcp
