apiVersion: v1
kind: Service
metadata:
  name: core
spec:
  selector:
    app: jumpserver
  ports:
    - name: app
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: ws
      protocol: TCP
      port: 8070
      targetPort: 8070