apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

configMapGenerator:
- name: nginxconf
  files:
  - nginx.conf

commonLabels:
  jumpserver: nginx

images:
- name: jumpserver:1.0
  newName: nginx
  newTag: 1.17.8

replicas:
- name: nginx
  count: 3
