apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

# configMapGenerator:
# - name: nginxconf
#   files:
#   - nginx.conf

commonLabels:
  jumpserver: nginx

images:
- name: jumpserver:1.0
  newName: harbor.xylink.com/xylink/jms_nginx
  newTag: 1.5.6

replicas:
- name: nginx
  count: 1
