apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: jumpserver
  ports:
    - name: app
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 39000
  type: NodePort