apiVersion: apps/v1
kind: Deployment
metadata:
  name: koko
  labels:
    app: jumpserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jumpserver
  template:
    metadata:
      labels:
        app: jumpserver
    spec:
      containers:
      - name: koko
        image: jumpserver:1.0
        ports:
        - containerPort: 2222
          name: ssh
          protocol: tcp
        - containerPort: 5000
          name: web
          protocol: tcp
