apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

commonLabels:
  jumpserver: koko

images:
- name: jumpserver:1.0
  newName: harbor.xylink.com/xylink/jms_koko
  newTag: 1.5.6

replicas:
- name: koko
  count: 1
