apiVersion: v1
kind: Service
metadata:
  name: koko
spec:
  selector:
    app: jumpserver
  ports:
    - name: ssh
      protocol: TCP
      port: 2222
      targetPort: 2222
    - name: web
      protocol: TCP
      port: 5000
      targetPort: 5000