apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: jumpserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jumpserver
  template:
    metadata:
      labels:
        app: jumpserver
    spec:
      containers:
      - name: redis
        image: jumpserver:1.0
        env:
          - name: REDIS_PORT
            value: "6379"
          - name: REDIS_PASSWORD
            value: "8URXPL2x3HZMi7xoGTdk3Upj"
        ports:
        - containerPort: 6379
          name: web
          protocol: TCP
