apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: redis
    app.kubernetes.io/name: jumpserver-redis-ha
    app.kubernetes.io/part-of: jumpserver
  name: jumpserver-redis-ha
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/component: redis
    app.kubernetes.io/name: jumpserver-redis-ha
    app.kubernetes.io/part-of: jumpserver
  name: jumpserver-redis-ha
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: redis
    app.kubernetes.io/name: jumpserver-redis-ha
    app.kubernetes.io/part-of: jumpserver
  name: jumpserver-redis-ha
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jumpserver-redis-ha
subjects:
- kind: ServiceAccount
  name: jumpserver-redis-ha